# Custom CircleCI configuration to support running CI for the "pkg/git" module separately.

version: 2.1

orbs:
  go: palantir/go@0.0.29
  godel: palantir/godel@0.0.29

homepath: &homepath
  homepath: /home/circleci

gopath: &gopath
  gopath: /home/circleci/go

executors:
  circleci-go:
    parameters:
      working_directory:
        type: string
        default: /home/circleci/go/src/github.com/palantir/distgo
    docker:
      - image: cimg/go:1.16-browsers
    working_directory: << parameters.working_directory >>

all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  verify-test-dist-publish:
    jobs:
      - godel/verify:
          name: verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          <<: *all-tags-filter
      - godel/test:
          name: test
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          <<: *all-tags-filter
          tags: none
      - godel/test:
          name: integration-test
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          <<: *all-tags-filter
          tags: integration
          parallelism: "2"
      - godel/dist:
          name: dist
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          <<: *all-tags-filter
      - godel/verify:
          name: pkg-git-verify-test
          checkout-path: /home/circleci/go/src/palantir/distgo
          include-tests: true
          executor:
            name: circleci-go
            working_directory: /home/circleci/go/src/palantir/distgo/pkg/git
          <<: *homepath
          <<: *gopath
          <<: *all-tags-filter
