version: 2.1

orbs:
  go: palantir/go@0.0.3
  godel: palantir/godel@0.0.2

executor-param: &executor-param
  executor:
    name: go/darwin-linux-no-cgo
    owner-repo: palantir/distgo

all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  dist-publish:
    jobs:
      - godel/verify:
          <<: *all-tags-filter
          <<: *executor-param
      - godel/test:
          <<: *all-tags-filter
          <<: *executor-param
      - godel/dist:
          <<: *all-tags-filter
          <<: *executor-param
      - godel/bintray-publish:
          requires:
            - godel/verify
            - godel/test
            - godel/dist
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$/
            branches:
              ignore: /.*/
          <<: *executor-param
          bintray-subject: palantir
          bintray-repo: releases
          bintray-product: distgo
