version: 2.1

orbs:
  godel: palantir/godel@0.0.1

owner-repo: &owner-repo
  owner: palantir
  repo: distgo

all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  dist-publish:
    jobs:
      - godel/verify:
          <<: *all-tags-filter
          <<: *owner-repo
      - godel/test:
          <<: *all-tags-filter
          <<: *owner-repo
      - godel/dist:
          <<: *all-tags-filter
          <<: *owner-repo
      - godel/bintray-publish:
          <<: *all-tags-filter
          <<: *owner-repo
          bintray-subject: palantir
          bintray-repo: releases
          bintray-product: distgo
          requires:
            - godel/verify
            - godel/test
            - godel/dist
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$/
            branches:
              ignore: /.*/
